### ISSUE TITLE
Date-Picker component nötig?

### ISSUE THREAD

**Issue by dragonfly28** [xdoo/lhm_polymer#4]
Die Komponente <paper-input type="date" ...>  zeigt auf meinem Browser (städtischer Firefox 45.9.0) nur ein triviales Textfeld. Scheint der Fallback des Browsers zu sein, wenn kein Date-Picker auf Browser-Seite implementiert ist. Andere Browser (z.B. Safari auf Android) haben hier eigene Controls implementiert und es poppen "Datepicker" auf. Brauchen wir hier eine andere Komponente wie z.B. den <vaadin-date-picker> um das einheitlicher zu machen oder ziehen wir uns darauf zurück, dass nur angezeigt wird, was die jeweiligen Browser hier zur Verfügung stellen?

**Comment by xdoo** [comment]
Ab der Version 51 kann dieses Problem so umgangen werden:

about:config
dom.forms.datetime -> set to true

Getestet habe ich das mit der Version 56.0 - da funktioniert es wunderbar.

**Comment by xdoo** [comment]
Ich bin dafür, dass wir die Komponente so verwenden und darauf drängen, dass ein Browser eingesetzt wird, der diese (HTML5) Funktionalität auch unterstützt. 

@rowe42

**Comment by dragonfly28** [comment]
D'accord. Keep it simple and stupid!

**Comment by rowe42** [comment]
Ich bin auch dafür, dass wir uns auf halbwegs aktuelle Browser-Versionen stützen. Das scheint derzeit
- Firefox 52.5 ESR
- Firefox 57
Ich bin weiterhin dafür, dass wir die aktuell auf dem Limux Basisclient installierte Version unterstützen: Firefox 45 ESR

Ich bin dagegen, dass jeder Benutzer erst unter about:config ein Flag setzen muss (wenn ich den Vorschlag oben tatsächlich so richtig verstehe).
